name: Hourly Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Update Page
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        # We use './' to tell Python "look in the current folder"
        run: python ./check_the_strait.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "HormuzBot"
          git config --global user.email "bot@ishormuzclosed.com"
          git add index.html
          git commit -m "Hourly update for May 2, 2026" || exit 0
          git push
