name: Hormez Monitor Update
on:
  workflow_dispatch:
  schedule:
    - cron: '45 * * * *'

permissions:
  contents: write

jobs:
  run-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Deps
        run: pip install requests
      - name: Run Script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python check_the_straight.py
      - name: Save Changes
        run: |
          git config --global user.name "HormezBot"
          git config --global user.email "bot@hormez.com"
          git add index.html counters.txt history.txt
          git commit -m "Manual Sync [skip ci]"
          git push origin main
